package terminal

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"io"
	"os"
	"path/filepath"
	"testing"
)

// The desktop app re-implements this protocol in TypeScript. These fixtures are
// the contract between the two: Go writes them, and desktop/test/frames.test.ts
// reads the same bytes back. Neither side can change the wire format without
// turning the other red.
//
// Regenerate with: go test ./internal/terminal -run Golden -update

var updateGolden = flag.Bool("update", false, "rewrite the golden frame fixtures")

const goldenDir = "testdata/frames"

// largeOutputSize exercises a payload far past any TCP or pipe buffer, where a
// parser that assumed one frame per read would break. It is checked by digest
// rather than committed: 4 MiB of filler in git buys nothing a hash does not.
const largeOutputSize = 4 << 20

func goldenFrames(t *testing.T) map[string][]byte {
	t.Helper()

	hello, err := json.Marshal(Hello{
		Role:  RoleInteractive,
		Cols:  120,
		Rows:  34,
		Since: 4096,
		Name:  "desktop",
	})
	if err != nil {
		t.Fatalf("marshal hello: %v", err)
	}

	status, err := json.Marshal(Status{
		State:   StateReady,
		Writer:  "phone",
		Viewers: 2,
		Cols:    120,
		Rows:    34,
	})
	if err != nil {
		t.Fatalf("marshal status: %v", err)
	}

	return map[string][]byte{
		"hello":    frameBytes(t, FrameHello, hello),
		"snapshot": frameBytes(t, FrameSnapshot, EncodeSnapshot(1<<40, []byte("\x1b[2J\x1b[H\x1b[32mready\x1b[0m"))),
		"output":   frameBytes(t, FrameOutput, []byte("\x1b[1mhello\x1b[0m \xf0\x9f\x8e\x89 \xe4\xb8\xad\xe6\x96\x87\r\n")),
		"input":    frameBytes(t, FrameInput, []byte{0x1b, '[', 'Z'}),
		"resize":   frameBytes(t, FrameResize, EncodeResize(120, 34)),
		"status":   frameBytes(t, FrameStatus, status),
		"exit":     frameBytes(t, FrameExit, encodeInt32(-1)),
		"ping":     frameBytes(t, FramePing, nil),
		"pong":     frameBytes(t, FramePong, nil),
		// Three frames back to back in one blob, so the TS parser is forced to
		// handle several frames per chunk rather than one.
		"stream": concatBytes(
			frameBytes(t, FrameOutput, []byte("first")),
			frameBytes(t, FramePing, nil),
			frameBytes(t, FrameOutput, []byte("second")),
		),
	}
}

func TestGoldenFramesMatchFixtures(t *testing.T) {
	frames := goldenFrames(t)

	if *updateGolden {
		if err := os.MkdirAll(goldenDir, 0o755); err != nil {
			t.Fatalf("create %s: %v", goldenDir, err)
		}
		for name, data := range frames {
			path := filepath.Join(goldenDir, name+".bin")
			if err := os.WriteFile(path, data, 0o644); err != nil {
				t.Fatalf("write %s: %v", path, err)
			}
		}
		if err := os.WriteFile(filepath.Join(goldenDir, "large-output.sha256"),
			[]byte(largeOutputDigest(t)+"\n"), 0o644); err != nil {
			t.Fatalf("write digest: %v", err)
		}
		t.Logf("wrote %d fixtures to %s", len(frames)+1, goldenDir)
		return
	}

	for name, want := range frames {
		path := filepath.Join(goldenDir, name+".bin")
		got, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s (run with -update to create it): %v", path, err)
		}
		if string(got) != string(want) {
			t.Errorf("%s: fixture does not match what the codec produces.\n got %x\nwant %x", name, got, want)
		}
	}
}

// TestGoldenLargeOutputDigest pins the 4 MiB frame by hash so the fixture
// directory stays small while both languages still agree on the bytes.
func TestGoldenLargeOutputDigest(t *testing.T) {
	if *updateGolden {
		t.Skip("written by TestGoldenFramesMatchFixtures")
	}
	path := filepath.Join(goldenDir, "large-output.sha256")
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	want := largeOutputDigest(t)
	if trimmed := string(got[:len(got)-1]); trimmed != want {
		t.Errorf("large output digest = %s, want %s", trimmed, want)
	}
}

// TestGoldenFramesRoundTrip proves the fixtures decode back to the values they
// were built from, so a fixture that is wrong in both directions still fails.
func TestGoldenFramesRoundTrip(t *testing.T) {
	for name, data := range goldenFrames(t) {
		if name == "stream" {
			continue
		}
		f, err := ReadFrame(newByteReader(data))
		if err != nil {
			t.Errorf("%s: ReadFrame: %v", name, err)
			continue
		}
		again, err := frameBytesErr(f.Type, f.Payload)
		if err != nil {
			t.Errorf("%s: re-encode: %v", name, err)
			continue
		}
		if string(again) != string(data) {
			t.Errorf("%s: round-trip changed the bytes", name)
		}
	}
}

func largeOutputDigest(t *testing.T) string {
	t.Helper()
	sum := sha256.Sum256(frameBytes(t, FrameOutput, largeOutputPayload()))
	return hex.EncodeToString(sum[:])
}

// largeOutputPayload is generated by a rule both languages can reproduce.
func largeOutputPayload() []byte {
	p := make([]byte, largeOutputSize)
	for i := range p {
		p[i] = byte(i % 251)
	}
	return p
}

func frameBytes(t *testing.T, typ FrameType, payload []byte) []byte {
	t.Helper()
	b, err := frameBytesErr(typ, payload)
	if err != nil {
		t.Fatalf("encode %s frame: %v", typ, err)
	}
	return b
}

func frameBytesErr(typ FrameType, payload []byte) ([]byte, error) {
	var buf sliceWriter
	if err := WriteFrame(&buf, typ, payload); err != nil {
		return nil, err
	}
	return buf, nil
}

func concatBytes(parts ...[]byte) []byte {
	var out []byte
	for _, p := range parts {
		out = append(out, p...)
	}
	return out
}

// sliceWriter is an io.Writer over a byte slice, avoiding a bytes.Buffer
// import for what is two appends.
type sliceWriter []byte

func (w *sliceWriter) Write(p []byte) (int, error) {
	*w = append(*w, p...)
	return len(p), nil
}

// byteReader is a minimal io.Reader over a slice.
type byteReader struct {
	b []byte
	i int
}

func newByteReader(b []byte) *byteReader { return &byteReader{b: b} }

func (r *byteReader) Read(p []byte) (int, error) {
	if r.i >= len(r.b) {
		return 0, io.EOF
	}
	n := copy(p, r.b[r.i:])
	r.i += n
	return n, nil
}
